### ISSUE TITLE
Question: Support for just plain 'ol TLD

### ISSUE THREAD

**Issue by decentral1se** [cavebeat/gandi-live-dns#15]
You have support for subdomains, that is great! I always get baz.foo.com routed correctly.

However, I just want to make sure my foo.com is also matching as well.

Is that handled by this script? If not, I can make some changes if we're in agreement.

**Comment by cmilanf** [comment]
Just use `@` as subdomain and it will work like a charm for your use case:

`subdomains = ["mail", "www", "@"]`

**Comment by decentral1se** [comment]
Solid, thanks!
