### ISSUE TITLE
State of the Project? Maintainers? Friendly Fork?

### ISSUE THREAD

**Issue by decentral1se** [cavebeat/gandi-live-dns#16]
Do you care? I kinda do. I can do it if you want!

EDIT: (when ticket was called 'Python3 Support')

**Comment by 3v1n0** [comment]
Since the main repo seems to be quite dead, maybe we can do an shared fork which is going to be actually maintened?

**Comment by decentral1se** [comment]
@3v1n0, yeah! I'd be totally down for this since I'm using it in a lot of my infrastructure. I'm on holidays now but in 2 weeks I'll be back. If you want to get started, I'll join then or I will create stuff then. I created a bunch of tickets already https://github.com/cavebeat/gandi-live-dns/issues/created_by/lwm.

**Comment by 3v1n0** [comment]
Good, I'll wait for your fork then since it's something you'll probably work more on.

**Comment by decentral1se** [comment]
https://github.com/gandi/gandi.cli is out!

**Comment by decentral1se** [comment]
Wait, wait, that's v4. OK, the fork is coming ...

**Comment by kay0u** [comment]
Coming you said? :D

**Comment by decentral1se** [comment]
Ah, yes, I did it and forgot to post back here ....

https://pypi.org/project/hdyndns/

Currently only supports Gandi (latest API) but could also potentially do others.

All contributions/feedback welcome! I'm using it on my home servers now ...

**Comment by kay0u** [comment]
Not on github?

**Comment by decentral1se** [comment]
https://git.coop/decentral1se/hdyndns - requires sign ups to log in right now :/ Email if you have issues!

**Comment by kay0u** [comment]
Many thanks
