### ISSUE TITLE
Error when running it on Kubuntu 18.10 !

### ISSUE THREAD

**Issue by vincegre** [cavebeat/gandi-live-dns#27]
Followed the tutorial but have the following error when running it (see below). It detects well my outside IP but has a problem with the record to update ! The record exists well and domain correctly setup so not sure what's problem ! As I was not sure about API key I generated a new one just to be sure ! If I ping my monsousdomaine.mondomaine it pings well so the record is well active in Gandi Live DNSs..

```
root@serveur:~/gandi-live-dns/src# ./gandi-live-dns.py 
Checking dynamic IP:  1.2.3.4
Error: HTTP Status Code  403 when trying to get IP from subdomain monsoudomaine
Traceback (most recent call last):
  File "./gandi-live-dns.py", line 124, in <module>
    main(args.force, args.verbose)
  File "./gandi-live-dns.py", line 103, in main
    dnsIP = get_dnsip(uuid)
  File "./gandi-live-dns.py", line 63, in get_dnsip
    print  json_object['message']
UnboundLocalError: local variable 'json_object' referenced before assignment
root@serveur:~/gandi-live-dns/src# 

```

**Comment by vincegre** [comment]
Someone else succeeded to get that script working ? I always get a 403 error :( I regenerated the API key but still the same !

**Comment by Pyanne** [comment]
Try this:
https://github.com/cavebeat/gandi-live-dns/pull/24/commits/ef63584f354d6d6a38acaa96a0e52dc7a7d323f0

**Comment by vincegre** [comment]
> Try this:
> [ef63584](https://github.com/cavebeat/gandi-live-dns/commit/ef63584f354d6d6a38acaa96a0e52dc7a7d323f0)

Unhappy same result :(

**Comment by petitsurfeur** [comment]
Same error, maybe because the DNS record didn't exist. 
I created it using a false IP (like 8.8.8.8) and then the command worked and the IP was updated.

Checking dynamic IP:  XX.XX.XX.XX
Checking IP from DNS Record YYY : 8.8.8.8
IP Address Mismatch - going to update the DNS Records for the subdomains with new IP XX.XX.XX.XX
Status Code: 201 , DNS Record Created , IP updated for YYY

**Comment by vincegre** [comment]
Closed that ticket that is still open without reason ! Not using Gandi services anymore....
