### ISSUE TITLE
Should it work as it ?

### ISSUE THREAD

**Issue by otyugh** [cavebeat/gandi-live-dns#4]
Hey,
I tried to configure the software but it ends up with the following error :
> Error: HTTP Status Code  404 when trying to get Zone UUID
> Unknown domain

Here is my config file : 
> api_secret = 'notongithub'
> api_endpoint = 'https://dns.api.gandi.net/api/v5'
> ttl = '300'
> 
> domain = 'arzinfo.pw'
> subdomains = ["www", "gnuw", "test"]
> 
> ifconfig = 'https://ifconfig.co'

Here is a small "print" I added line 36 on the main program (where the error was coming up) : 
> print 'curl', url, '-H "X-Api-Key:',config.api_secret,'"'

And using the printed content :
> $curl https://dns.api.gandi.net/api/v5/domains/arzinfo.pw -H "X-Api-Key: notongithub"
> {"code": 404, "message": "Unknown domain", "object": "LocalizedHTTPNotFound", "cause": "Not Found"}

**Comment by CyrilSiman** [comment]
I had the same error, but I migrate all my dns records to the new Gandi interface and all works for me now. Maybe it's the same problem for you.

**Comment by otyugh** [comment]
It seems you were right, it did the trick. :)
I had an error first ("Error: HTTP Status Code  404 when trying to get IP from subdomain www") but it was because I had defined a sub (here "www") with CNAME. Changed it to A. Works like a charm now. 
Thanks !
And damn the soul of all thoses ISP that does not provide any fix IP where there is no shortage to be had since IPv6. é_è
