### ISSUE TITLE
SyntexError

### ISSUE THREAD

**Issue by ok38** [cavebeat/gandi-live-dns#6]
On Archlinux 64 i have a invalid syntax :

`  File "./gandi-live-dns.py", line 25
    print 'Checking dynamic IP: ' , r._content.strip('\n')
                                ^
SyntaxError: invalid syntax
`

**Comment by jcharaoui** [comment]
It seems this script is not (yet?) compatible with Python 3.

**Comment by ok38** [comment]
Python 2.7.14-1 (rpi3) is installed...

`
Python 2 will happily run alongside Python 3. You need to specify python2 in order to run this version.

$ python2 myScript.py

https://wiki.archlinux.org/index.php/python#Python_2
`

I just saw this. I'll try tonight. Thanks.
