### ISSUE TITLE
No subdomains

### ISSUE THREAD

**Issue by bavay** [cavebeat/gandi-live-dns#7]
Hello!

I tried to change your script so this would work without subdomains, but I did not manage to make it work... (either "UnboundLocalError: local variable 'json_object' referenced before assignment" when not modifying anything or "TypeError: list indices must be integers, not str" when trying to remove the "subdomains[]" stuff).

**Comment by NuclearFuzion** [comment]
You actually have lots of default subdomains: @, www, blog, imap, pop, smtp, etc....

The one I guess you're trying to update is @. I entered "@" as first subdomain and the script runs fine. Still waiting DNS propagation, but at list the script goes with no error output.

**Comment by bavay** [comment]
Well, now I feel stupid :-) Anyway, thanks a lot for your answer! Now it works perfectly fine... I never realized that "@" was for the host name itself (I don't even know how to name it, but at least now I've understood it). Thanks again, and thanks for this very useful dns updater!
